---
name: Merge Schedule
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
      - cron: "5 * * * *"

jobs:
  merge_schedule:
    if: |
    github.event_name = 'schedule' || github.event_name = 'pull_request' &&
    contains(github.event.pull_request.labels.*.name, 'auto schedule merging')
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v2
        with:
          # Merge method to use. Possible values are merge, squash or
          # rebase. Default is merge.
          merge_method: merge
          # Time zone to use. Default is UTC.
          time_zone: "UTC"
          # Require all pull request statuses to be successful before
          # merging. Default is `false`.
          require_statuses_success: "true"
          # Label to apply to the pull request if the merge fails. Default is
          # `automerge-fail`.
          automerge_fail_label: "merge-schedule-failed"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
